vich_uploader:
    twig: true
    db_driver: orm

    mappings:
        brand_logo:
            uri_prefix: /images/brands
            upload_destination: '%kernel.project_dir%/public_html/images/brands'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
