<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250818170537 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
//        $this->addSql('DROP TABLE b_file');
//        $this->addSql('DROP TABLE b_iblock_element');
//        $this->addSql('DROP TABLE b_iblock_element_property');
//        $this->addSql('ALTER TABLE product ADD preview VARCHAR(255) DEFAULT NULL, ADD image VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
//        $this->addSql('CREATE TABLE b_file (ID INT AUTO_INCREMENT NOT NULL, TIMESTAMP_X DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, MODULE_ID VARCHAR(50) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, HEIGHT INT DEFAULT NULL, WIDTH INT DEFAULT NULL, FILE_SIZE BIGINT DEFAULT NULL, CONTENT_TYPE VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'IMAGE\' COLLATE `utf8mb3_unicode_ci`, SUBDIR VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, FILE_NAME VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, ORIGINAL_NAME VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, DESCRIPTION VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, HANDLER_ID VARCHAR(50) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, EXTERNAL_ID VARCHAR(50) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, INDEX IX_B_FILE_EXTERNAL_ID (EXTERNAL_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
//        $this->addSql('CREATE TABLE b_iblock_element (ID INT AUTO_INCREMENT NOT NULL, TIMESTAMP_X DATETIME DEFAULT NULL, MODIFIED_BY INT DEFAULT NULL, DATE_CREATE DATETIME DEFAULT NULL, CREATED_BY INT DEFAULT NULL, IBLOCK_ID INT DEFAULT 0 NOT NULL, IBLOCK_SECTION_ID INT DEFAULT NULL, ACTIVE CHAR(1) CHARACTER SET utf8mb3 DEFAULT \'Y\' NOT NULL COLLATE `utf8mb3_unicode_ci`, ACTIVE_FROM DATETIME DEFAULT NULL, ACTIVE_TO DATETIME DEFAULT NULL, SORT INT DEFAULT 500 NOT NULL, NAME VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, PREVIEW_PICTURE INT DEFAULT NULL, PREVIEW_TEXT TEXT CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, PREVIEW_TEXT_TYPE VARCHAR(4) CHARACTER SET utf8mb3 DEFAULT \'text\' NOT NULL COLLATE `utf8mb3_unicode_ci`, DETAIL_PICTURE INT DEFAULT NULL, DETAIL_TEXT LONGTEXT CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, DETAIL_TEXT_TYPE VARCHAR(4) CHARACTER SET utf8mb3 DEFAULT \'text\' NOT NULL COLLATE `utf8mb3_unicode_ci`, SEARCHABLE_CONTENT TEXT CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, WF_STATUS_ID INT DEFAULT 1, WF_PARENT_ELEMENT_ID INT DEFAULT NULL, WF_NEW CHAR(1) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, WF_LOCKED_BY INT DEFAULT NULL, WF_DATE_LOCK DATETIME DEFAULT NULL, WF_COMMENTS TEXT CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, IN_SECTIONS CHAR(1) CHARACTER SET utf8mb3 DEFAULT \'N\' NOT NULL COLLATE `utf8mb3_unicode_ci`, XML_ID VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, CODE VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, TAGS VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, TMP_ID VARCHAR(40) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, WF_LAST_HISTORY_ID INT DEFAULT NULL, SHOW_COUNTER INT DEFAULT NULL, SHOW_COUNTER_START DATETIME DEFAULT NULL, INDEX ix_iblock_element_1 (IBLOCK_ID, IBLOCK_SECTION_ID), INDEX ix_iblock_element_3 (WF_PARENT_ELEMENT_ID), INDEX ix_iblock_element_4 (IBLOCK_ID, XML_ID, WF_PARENT_ELEMENT_ID), INDEX ix_iblock_element_code (IBLOCK_ID, CODE), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
//        $this->addSql('CREATE TABLE b_iblock_element_property (ID INT AUTO_INCREMENT NOT NULL, IBLOCK_PROPERTY_ID INT NOT NULL, IBLOCK_ELEMENT_ID INT NOT NULL, VALUE TEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, VALUE_TYPE CHAR(4) CHARACTER SET utf8mb3 DEFAULT \'text\' NOT NULL COLLATE `utf8mb3_unicode_ci`, VALUE_ENUM INT DEFAULT NULL, VALUE_NUM NUMERIC(18, 4) DEFAULT NULL, DESCRIPTION VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, INDEX ix_iblock_element_prop_enum (VALUE_ENUM, IBLOCK_PROPERTY_ID), INDEX ix_iblock_element_prop_num (VALUE_NUM, IBLOCK_PROPERTY_ID), INDEX ix_iblock_element_prop_val (VALUE(50), IBLOCK_PROPERTY_ID, IBLOCK_ELEMENT_ID), INDEX ix_iblock_element_property_1 (IBLOCK_ELEMENT_ID, IBLOCK_PROPERTY_ID), INDEX ix_iblock_element_property_2 (IBLOCK_PROPERTY_ID), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
//        $this->addSql('ALTER TABLE product DROP preview, DROP image');
    }
}
